import React from 'react';
import { AbsoluteFill, useCurrentFrame, useVideoConfig } from 'remotion';
import {
  fadeUp,
  popIn,
  Background,
  SafeArea,
  GlowOrb,
  Grid,
  AnimatedCharacters,
  TypewriterText,
  Vignette,
  palettes,
} from '@oanim/core';
import { spaceGrotesk, jetBrainsMono } from '../fonts';

const colors = palettes.sunset;

/**
 * Scene 6: The CTA — 180 frames (6s)
 * AnimatedCharacters "Start creating" → TypewriterText command → URL → closing
 */
export const TheCTA: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  return (
    <AbsoluteFill>
      <Background
        gradient={`radial-gradient(ellipse at 50% 50%, ${colors.bgAlt}, ${colors.bg})`}
      />
      <Grid color="rgba(249, 115, 22, 0.03)" cellSize={80} />
      <GlowOrb color="rgba(249, 115, 22, 0.25)" x={50} y={45} size={700} />
      <GlowOrb color="rgba(245, 158, 11, 0.12)" x={35} y={60} size={500} />
      <Vignette intensity={0.4} />

      <SafeArea
        style={{
          justifyContent: 'center',
          alignItems: 'center',
          gap: 28,
        }}
      >
        <div
          style={{
            fontSize: 80,
            fontWeight: 800,
            fontFamily: spaceGrotesk,
            color: colors.text,
            textAlign: 'center',
            lineHeight: 1.1,
          }}
        >
          <AnimatedCharacters text="Start creating" delay={0.15} stagger={0.035} />
        </div>

        <div
          style={{
            ...fadeUp({ frame, fps, delay: 1.2 }),
            fontSize: 28,
            fontFamily: jetBrainsMono,
            color: colors.primary,
            textAlign: 'center',
            padding: '16px 32px',
            background: 'rgba(249, 115, 22, 0.08)',
            borderRadius: 12,
            border: '1px solid rgba(249, 115, 22, 0.2)',
          }}
        >
          <TypewriterText
            text="npx oanim init my-video"
            delay={1.5}
            charsPerSecond={20}
          />
        </div>

        <div style={popIn({ frame, fps, delay: 3.5 })}>
          <div
            style={{
              fontSize: 48,
              fontWeight: 700,
              fontFamily: spaceGrotesk,
              color: colors.text,
              textAlign: 'center',
            }}
          >
            open-animate.com
          </div>
        </div>

        <div
          style={{
            ...fadeUp({ frame, fps, delay: 4.8 }),
            fontSize: 20,
            color: colors.textMuted,
            textAlign: 'center',
            fontStyle: 'italic',
          }}
        >
          This video was made with oanim — images, video, and audio all generated by AI.
        </div>
      </SafeArea>
    </AbsoluteFill>
  );
};
